<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ClientInformation.Shared\ClientInformation.Shared.csproj" />
    <ProjectReference Include="..\ClientInformation.Data\ClientInformation.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\Client.ico" CopyToOutputDirectory="PreserveNewest"/>
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\Client.ico</ApplicationIcon>
  </PropertyGroup>

</Project>
